### ISSUE TITLE
PCFX does not lock access to BRAM

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#113]
The lock on Backup memory does not appear to be implemented.
On a real system, you will not be able to read the backup memory directly after booting a game; it will need to be unlocked first.

Perhaps it is realistic to allow the debugger to view the data, but with a clear marker that it is locked - either a "LOCKED" message in text in an obvious area, or perhaps the data color should be red or something.

**Comment by pceDev16** [comment]
Closed per the merge of #116
