### ISSUE TITLE
Enhancement: Update PC-FX palette editor

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#114]
PC-FX palette editor is currently 8-bit, and show no information about how values create on-screen colours.
Update PC-FX palette editor to behave analagously to PCE palette editor (i.e. with colour swatches on the right side)

**Comment by dshadoff** [comment]
Pull request #115 intended to address this

**Comment by pceDev16** [comment]
Closed by merging #115 !
