### ISSUE TITLE
BUG/Portions of the intro to Yuna 2 (Japanese) do not display due to oddities in video handling

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#12]
This is believed to be a result of:
```
  - at the second rcr, sprites and bg are both disabled,
    forcibly blanking the remainder of the screen.
mednafen does not like having the lower bound of the crop set higher than
0xF2. this will result in the lower-bound crop triggering after the vsync
handler, which ends up disable bg for the entire screen.
this appears to just be an emulation bug, though.
using a lower value like 0xF0 instead will fix it regardless.
```

**Comment by dshadoff** [comment]
More detail can be found in this conversation:
[HERE](https://pcengine.proboards.com/post/16527/thread)

**Comment by Turboxray** [comment]
Wrote a test demo. From recently tests, when the VDC exists vsync pulse with waiting state (whether VCE asserts vsync and ends it, or it expires), the display regs in CR for BG and Sprites are latched. And if BG=SPRITE=0, then the frame is disabled and in "burst mode" for the entire frame.

**Comment by dshadoff** [comment]
Integrated and tested

**Comment by dshadoff** [comment]
Relocating burst mode unfortunately from https://github.com/pceDev16/mednafenPceDev/pull/50 had side effects; we should roll this back and try to find a solution without side effects.

**Comment by pceDev16** [comment]
#50 has been rolled back.

**Comment by dshadoff** [comment]
Validated against pull request #89
