### ISSUE TITLE
Fix up the six button controller for pc engine cd games

### ISSUE THREAD

**Issue by Mrmath7** [pce-devel/mednafenPceDev#122]
Can you fix up the six button controller for pc engine cd games, because six button controller is out of control for pc engine cd games.

**Comment by dshadoff** [comment]
I have no idea what you are talking about - could you please provide descriptive examples of what you are seeing:
- what is your setup
- what game(s) are you trying
- what do you experience

It should be noted that very few games actually support 6-button controllers, so if you are trying to use 6-button controllers on a game which doesn't support it, you may experience very strange behaviour.
