### ISSUE TITLE
After Burner II crashes soon after start

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#123]
After Burner II for PCE crashes roughly within a second of loading.
This was introduced by fix #121 .  Rather, I should say that it was "revealed" by that fix.

**Comment by pceDev16** [comment]
Hi @dshadoff, 
I am not seeing this behavior here with the current repo state on macOS:

_Starting Mednafen 1.29.0.pceDev-1.1 (219f8bb) built on Sun Apr  2 12:05:15 PDT 2023 
 Build information:
   Compiled with gcc Apple LLVM 14.0.0 (clang-1400.0.29.202)
   Compiled against zlib 1.2.11, running with zlib 1.2.11(flags=0x000000a9)
   Compiled against libiconv 11.1, running with libiconv 11.1
   Compiled against SDL 2.26.4(SDL-release-2.26.4-0-g07d0f51fa), running with SDL 2.26.4(SDL-release-2.26.4-0-g07d0f51fa)
   Running with libFLAC 1.4.2_
   
Using:
_ac0cdee014e725e428fde5774751ff8d  After Burner II (Japan).pce_

**Comment by dshadoff** [comment]
This would have been fixed by the commit "[Update when Timer interrupt is sampled]" on April 1
