### ISSUE TITLE
Documentation: would be nice to have compile notes at the top level

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#20]
I never know how to compile the package, and always felt that the included instructions weren't clear enough.

Now that this repo can be update by us, let's have some kind of top-level README instructions for compiling.
As a start, I found this page which actually gave me everything I needed to compile on linux:
http://jeremywininger.blogspot.com/2013/08/hey-lets-compile-mednafen-emulator.html

All I need to do was test and update settings.
(in particular, "sound.device" as per information here:  https://mednafen.github.io/documentation/#Section_troubleshooting_nosoundlinux  and here: https://mednafen.github.io/documentation/#sound.device )

**Comment by pceDev16** [comment]
#22 adds in the initial example of this. Will leave this issue open for now to add compile notes other platforms.

**Comment by dshadoff** [comment]
#75 adds in the Windows cross-compile now too.

**Comment by pceDev16** [comment]
and macOS compile notes have been added in as well, just in time for the 1.0 release.
