### ISSUE TITLE
Verify whether the VCE chroma bit affects number of lines per field

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#25]
There is a bit on VCE which controls artifact visibility - one value reduces them for text legibility, and the other value enhances them for artistic presentation.

This flag modifies whether the VCE produces 262 or 263 lines per field, which in turn affects refresh frequency.  While I am not aware of any games which rely on this behavior, it does affect things such as the MDFourier suite timing.

**Comment by dshadoff** [comment]
A quick review of the code implies that it is hardcoded at 263 lines and this may not be as trivial as expected.

**Comment by dshadoff** [comment]
Further inspection of the code implies that this is tracked, at least to some degree.

vce.cpp sets a boolean called "lc263" which may or may not be used consistently; however, at least there is some intent into this.

Also:
- The buffers are all allocated to 263 lines, which makes sense
- Certain areas of code use mosulo 263 arithmetic for some reason - this may not be universally appropriate.  Needs further investigation and testing.

**Comment by pceDev16** [comment]
We are accurate (enough) and the VCE Chroma bit does affect the number of lines per field and refresh frequency.

Real / Physical Duo filter on: 59.828213 Hz signal (16.714522ms per frame)
Mednafen 1.29.0.pceDev-1.0 PCE filter on: 59.825773 Hz signal (16.715204ms per frame)

Real / Physical SGX filter off: 60.053985 Hz signal (16.651684ms per frame) from Audio file
Mednafen 1.29.0.pceDev-1.0 SGX filter off: 60.054464 Hz signal (16.651551ms per frame) from Audio file
