### ISSUE TITLE
Debugger request: Sprite "bounding box" display

### ISSUE THREAD

**Issue by dshadoff** [pce-devel/mednafenPceDev#3]
In the same way that background layer and sprite layer can be turned on or off, it would be nice to be able to display the "bounding box" of sprites.

To a lesser degree, a "character grid" might also be useful.

**Comment by pceDev16** [comment]
![SGX_Dai_BBox_Feature](https://user-images.githubusercontent.com/95596143/169720537-8d627180-4402-4a73-b1dd-354672ca172f.png)

**Comment by dshadoff** [comment]
Validated.
