### ISSUE TITLE
BUG: Bonk's Adventure flashes title card logo when launching the game.

### ISSUE THREAD

**Issue by pceDev16** [pce-devel/mednafenPceDev#8]
Using Mednafen 1.27.1, Bonk's Adventure (`3aa21326050c489ea867de05dd6cb7e5  Bonk's Adventure (USA).pce`), quickly flashes the title card logo for 1 frame when launching the game. This doesn't happen on real hardware.

![bla](https://user-images.githubusercontent.com/95596143/145723614-daa9e1f6-8d99-4ae5-8a83-fa88dd75b6e1.gif)

**Comment by pceDev16** [comment]
Testing with using  "`-video.force_bbclear 1`" on the newer 1.28.0 --UNSTABLE-- branch doesn't appear to fix this issue.

**Comment by pceDev16** [comment]
Closed, Fixed by #50

**Comment by pceDev16** [comment]
Relocating burst mode unfortunately from #50 did not fix the issues.

**Comment by dshadoff** [comment]
Rather, it fixed this issue but had side effects on some other games, such as random blank flashes on SF2 as per MrJ.
