### ISSUE TITLE
jbrandwood's "happyeyes" in disassembler window on Linux

### ISSUE THREAD

**Issue by 0x8BitDev** [pce-devel/mednafenPceDev#97]
I've found that jbrandwood's "happyeyes" doesn't apply in disassembler window on Linux. I use Debian 9.9.0

**Mednafen Linux build from github repository:**
![mednafen_Linux_build_Debian_9 9 0](https://user-images.githubusercontent.com/49449254/178148996-0f39c79d-6b7c-4933-b98d-e3aaf2e1c633.png)

**Mednafen 1.29.0.pceDev-1.0-win64-release**
![mednafen-1 29 0 pceDev-1 0-win64](https://user-images.githubusercontent.com/49449254/178148938-9985dc9e-c391-4064-b8c1-95f7eea06081.png)

**Comment by dshadoff** [comment]
It looks to me like you've started with a brand new mednafen.cfg file, and will need to reapply some defaults.
In particular, the only thing I see that's "not correct" above, requires this update:

```
;Disassembly font size.
pce.debugger.disfontsize 6x13
```

The lines already exist, but the font size value needs to be adjusted (for some reason, there is no default embedded in the code).

**Comment by 0x8BitDev** [comment]
I uninstalled the old Mednafen before installing the Pce Dev version.
Now, after your changes, my eyes are happy to look at the disassembler window. :)) Thanks!
