### ISSUE TITLE
mednafen's emulation of PCE CD-ROM command $DE "read-toc" is faulty.

### ISSUE THREAD

**Issue by jbrandwood** [pce-devel/mednafenPceDev#98]
Mednafen is only returning 2-bytes for a type "0" read-toc, and 3-bytes for a type "1" read-toc.

Real PCE hardware returns 4-bytes for these commands, which is what the System Card requests.

The fix is simple. Line 219 in file "scsicd-pce-commands.inc" should be ...

  case 0x0:
   data_in[0] = U8_to_BCD(toc.first_track);
   data_in[1] = U8_to_BCD(toc.last_track);
   data_in[2] = 0;
   data_in[3] = 0;

   data_in_size = 4;
   break;

  case 0x1:
   {
    uint8 m, s, f;

    LBA_to_AMSF(toc.tracks[100].lba, &m, &s, &f);

    data_in[0] = U8_to_BCD(m);
    data_in[1] = U8_to_BCD(s);
    data_in[2] = U8_to_BCD(f);
    data_in[3] = 0;

    data_in_size = 4;
   }

**Comment by pceDev16** [comment]
Also adding in the updated SuperGrafx-CD detection updates into the PR #99

**Comment by pceDev16** [comment]
Merged in 1.1 Release.
